{{- if .Values.ciliumPolicy.enabled }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: intercept-tls-policy
  namespace: {{ .Values.namespace.workload }}
  labels:
    {{ include "cilium-tls-intercept.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-policy
spec:
  endpointSelector:
    matchLabels:
      app: intercept-workload
  egress:
  {{- if .Values.intercept.github.enabled }}
  # GitHub traffic interception
  - toFQDNs:
    {{- range .Values.intercept.github.domains }}
    - matchPattern: {{ . | quote }}
    {{- end }}
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      terminatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-github-tls
      originatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-upstream-ca-bundle
      {{- if .Values.ciliumPolicy.githubRules }}
      rules:
        http:
        {{- range .Values.ciliumPolicy.githubRules }}
        - method: {{ .method }}
          path: {{ .path | quote }}
        {{- end }}
      {{- end }}
  {{- end }}

  {{- if .Values.intercept.aws.enabled }}
  # AWS traffic interception
  - toFQDNs:
    {{- range .Values.intercept.aws.domains }}
    - matchPattern: {{ . | quote }}
    {{- end }}
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      terminatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-aws-tls
      originatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-upstream-ca-bundle
  {{- end }}

  {{- if .Values.intercept.google.enabled }}
  # Google APIs traffic interception
  - toFQDNs:
    {{- range .Values.intercept.google.domains }}
    - matchPattern: {{ . | quote }}
    {{- end }}
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      terminatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-google-tls
      originatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-upstream-ca-bundle
  {{- end }}

  {{- if .Values.intercept.custom.enabled }}
  # Custom domains interception
  - toFQDNs:
    {{- range .Values.intercept.custom.domains }}
    - matchPattern: {{ . | quote }}
    {{- end }}
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP
      terminatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-custom-tls
      originatingTLS:
        secret:
          namespace: cilium-secrets
          name: intercept-upstream-ca-bundle
  {{- end }}

  # Allow DNS
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: kube-system
        k8s:k8s-app: kube-dns
    toPorts:
    - ports:
      - port: "53"
        protocol: UDP

  # Allow general HTTP/HTTPS without interception (fallback)
  - toEntities:
    - world
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
    - ports:
      - port: "443"
        protocol: TCP
{{- end }}