services:
  mitmproxy-boundary:
    build: .
    container_name: mitm-boundary-proxy
    volumes:
      - ${OPA_POLICY_DIR:-./opa-policies}:/app/bundle:ro
      - mitmproxy-certs:/home/mitmproxy/.mitmproxy
    networks:
      - mitm-filtered
      - bridge
    ports:
      - "8080:8080"  # Proxy port (accessible from host)
    environment:
      - LISTEN_HOST=0.0.0.0
    restart: unless-stopped

networks:
  mitm-filtered:
    external: true
    name: mitm-filtered
  bridge:
    driver: bridge

volumes:
  mitmproxy-certs:
    name: mitm-boundary-certs