version: '3.8'

networks:
  mitm-filtered:
    external: true
    name: mitm-filtered

services:
  test-container:
    build: .
    networks:
      - mitm-filtered
    environment:
      - HTTP_PROXY=http://mitm-boundary-proxy:8080
      - HTTPS_PROXY=http://mitm-boundary-proxy:8080
      - http_proxy=http://mitm-boundary-proxy:8080
      - https_proxy=http://mitm-boundary-proxy:8080
      - NO_PROXY=localhost,127.0.0.1,mitm-boundary-proxy
      - no_proxy=localhost,127.0.0.1,mitm-boundary-proxy