apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-curl
  namespace: kyverno-intercept
  labels:
    app: test-curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-curl
  template:
    metadata:
      labels:
        app: test-curl
        # REQUIRED: This label triggers Kyverno policy to inject TLS interception sidecars
        # Without this label, pod will run normally without interception
        intercept-proxy/enabled: "true"
    spec:
      # IMPORTANT: Application container MUST run with a UID different from sidecars
      # Sidecar UIDs (reserved, do NOT use for application):
      #   - 101: Envoy proxy
      #   - 102: OPA sidecar
      #   - 103: SDS service
      #
      # If your container runs as one of these UIDs, traffic will bypass interception
      # due to iptables UID-based exclusion rules (prevents infinite loops)
      #
      # Common safe UIDs for applications: 1000, 12345, or any UID > 1000 except 101-103
      securityContext:
        runAsUser: 12345   # Application UID - must NOT be 101, 102, or 103
        runAsGroup: 12345
        fsGroup: 12345
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        # NOTE: No proxy environment variables needed!
        # Traffic is transparently redirected via iptables rules set up by init container
        #
        # The following are automatically configured by Kyverno:
        # - CA certificate mounted and trusted at /etc/ssl/certs/ca-certificates.crt
        # - SSL_CERT_FILE and other CA env vars injected
        # - iptables rules redirect ports 80/443 to Envoy (port 15001)
        #
        # Application can make HTTPS requests normally:
        #   curl https://api.github.com  # Works without -k flag!
        #
        # Port restrictions for application container:
        # - ✓ Can use: Ports 1024-14999, 15100-65535 on localhost
        # - ✗ Cannot access: Ports 0-1023 (privileged ports)
        # - ✗ Cannot access: Ports 15000-15099 (reserved for sidecars)
