{{- if .Values.networkPolicy.enabled }}
# NetworkPolicy to block cloud metadata service access from intercepted pods.
# This is part of the defense-in-depth for SECURITY_ASSESSMENT.md vulnerability #3.
#
# Security Model:
# - PRIMARY: automountServiceAccountToken: false (Kyverno mutation) removes K8s API credentials
# - SECONDARY: This NetworkPolicy blocks cloud metadata service (credential theft prevention)
#
# How it works:
# - Kubernetes NetworkPolicy is allow-list based
# - We allow DNS (required for hostname resolution) and HTTP/HTTPS
# - We explicitly exclude cloud metadata service (169.254.169.254) from allowed destinations
# - This prevents IMDS credential theft in cloud environments (AWS, GCP, Azure)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-block-k8s-api
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: security
spec:
  # Apply to pods with intercept-proxy enabled
  podSelector:
    matchLabels:
      "{{ .Values.kyverno.annotationKey }}": "{{ .Values.kyverno.annotationValue }}"
  policyTypes:
    - Egress
  egress:
    # Allow DNS resolution (required for hostname lookups)
    - to:
        - namespaceSelector: {}  # Allow DNS to any namespace (CoreDNS)
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow HTTP traffic, excluding blocked CIDRs (e.g., cloud metadata service)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              {{- range .Values.networkPolicy.blockedCIDRs }}
              - {{ . }}
              {{- end }}
      ports:
        - protocol: TCP
          port: 80

    # Allow HTTPS traffic, excluding blocked CIDRs (e.g., cloud metadata service)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              {{- range .Values.networkPolicy.blockedCIDRs }}
              - {{ . }}
              {{- end }}
      ports:
        - protocol: TCP
          port: 443

    {{- if .Values.networkPolicy.allowIntraNamespace }}
    # Allow communication within the same namespace (for sidecars)
    # This is needed because Envoy/OPA/xDS sidecars communicate via localhost
    # which is not affected by NetworkPolicy, but inter-pod communication is
    - to:
        - podSelector: {}  # Same namespace
      ports:
        - protocol: TCP
    {{- end }}

    {{- range .Values.networkPolicy.additionalAllowedEgress }}
    # Additional allowed egress rules from values
    - {{ toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
