{{- if .Values.opa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-policy
  namespace: {{ .Values.namespace }}
data:
  policy.rego: |
    package intercept

    import future.keywords.if
    import future.keywords.in

    default allow = false

    # Parse the incoming request
    http_request := input.attributes.request.http

    # Extract request details
    method := http_request.method
    path := http_request.path

    # SECURITY: For HTTPS traffic, verify Host header matches TLS certificate CN
    # For HTTP traffic, Host header is safe to use (no TLS to spoof)
    tls_principal := input.attributes.destination.principal
    http_host := http_request.host

    # Use TLS CN if available (HTTPS), otherwise use Host header (HTTP)
    # Handle both undefined and empty string cases
    host := tls_principal if {
        tls_principal
        tls_principal != ""
    }

    host := http_host if {
        not tls_principal
    }

    host := http_host if {
        tls_principal == ""
    }

    # SECURITY CHECK: For HTTPS, reject if Host header doesn't match TLS certificate CN
    # This prevents Host header manipulation attacks on TLS connections
    host_header_mismatch if {
        tls_principal
        tls_principal != ""
        tls_principal != http_host
    }

    # Check if domain is in allowed list (restricted to GET/HEAD)
    allow if {
      not host_header_mismatch  # Security check: reject if Host/TLS mismatch
      host in data.allowed_domains
      method in ["GET", "HEAD"]
    }

    # Check if domain is in unrestricted list (all methods allowed)
    allow if {
      not host_header_mismatch  # Security check: reject if Host/TLS mismatch
      host in data.unrestricted_domains
    }

    # GitHub-specific rules
    allow if {
      not host_header_mismatch  # Security check: reject if Host/TLS mismatch
      data.github_read_access_enabled
      contains(host, "github")
      method in ["GET", "HEAD"]
    }

    # GitHub write access for specific users/repos
    allow if {
      not host_header_mismatch  # Security check: reject if Host/TLS mismatch
      contains(host, "github")
      method in ["POST", "PUT", "PATCH", "DELETE"]
      github_write_allowed
    }

    github_write_allowed if {
      # Extract repo from path (e.g., /repos/owner/repo/...)
      regex.match("^/repos/([^/]+/[^/]+)", path)
      repo := regex.find_all_string_submatch_n("^/repos/([^/]+/[^/]+)", path, 1)[0][1]
      repo in data.github_allowed_repos
    }

    github_write_allowed if {
      # Extract user from path
      regex.match("^/users/([^/]+)", path)
      user := regex.find_all_string_submatch_n("^/users/([^/]+)", path, 1)[0][1]
      user in data.github_allowed_users
    }

    # Aggregate all domains that require TLS certificates
    # This endpoint is queried by the SDS control plane to pre-generate certificates
    required_domains := {domain | domain := all_domains[_]}

    all_domains := array.concat(array.concat(data.allowed_domains, data.unrestricted_domains), array.concat(github_domains, aws_domains))

    # GitHub domains that need certificates
    github_domains := ["github.com", "api.github.com"] if {
      data.github_read_access_enabled
    } else := []

    # AWS domains that need certificates
    aws_domains := [sprintf("%s.amazonaws.com", [service]) | service := data.aws_allowed_services[_]] if {
      data.aws_access_enabled
    } else := []

  data.yml: |
    # Domains with restricted access (only GET/HEAD allowed)
    allowed_domains:
    {{- range .Values.opa.policy.allowedDomains }}
      - {{ . | quote }}
    {{- end }}

    # Domains with unrestricted access (all HTTP methods allowed)
    unrestricted_domains:
    {{- range .Values.opa.policy.unrestrictedDomains }}
      - {{ . | quote }}
    {{- end }}

    # GitHub access control configuration
    github_read_access_enabled: {{ .Values.opa.policy.githubReadAccessEnabled }}

    # GitHub users allowed to perform write operations
    github_allowed_users:
    {{- range .Values.opa.policy.githubAllowedUsers }}
      - {{ . | quote }}
    {{- end }}

    # Specific GitHub repositories allowed for write operations
    github_allowed_repos:
    {{- range .Values.opa.policy.githubAllowedRepos }}
      - {{ . | quote }}
    {{- end }}

    # AWS domains configuration
    aws_access_enabled: {{ .Values.opa.policy.awsAccessEnabled | default false }}

    aws_allowed_services:
    {{- range .Values.opa.policy.awsAllowedServices }}
      - {{ . | quote }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    telemetry:
      reporting_disabled: true

    plugins:
      envoy_ext_authz_grpc:
        addr: :{{ .Values.opa.grpcPort }}
        path: intercept/allow
        dry_run: false
        enable_reflection: true

    decision_logs:
      console: true

    status:
      console: true
{{- end }}