{{- if .Values.opa.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-policy
  namespace: {{ .Values.namespace }}
data:
  policy.rego: {{ .Files.Get "policies/policy.rego" | quote }}
  data.yml: |
{{ tpl (.Files.Get "policies/data.yml.tpl") . | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-opa-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    telemetry:
      reporting_disabled: true

    plugins:
      envoy_ext_authz_grpc:
        addr: ":{{ .Values.opa.grpcPort }}"
        path: intercept/allow
        dry_run: false
        enable_reflection: true

    decision_logs:
      console: true

    status:
      console: true
{{- end }}